### ISSUE TITLE
Failed to load the aligner package

### ISSUE THREAD

**Issue by Rdfenix** [adrianlee44/atom-aligner#30]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.11
**System**: Unknown Windows Version
**Thrown From**: [aligner](https://github.com/adrianlee44/atom-aligner) package, v0.16.0

### Stack Trace

Failed to load the aligner package

```
At Cannot find module 'extend'

Error: Cannot find module 'extend'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (C:\Users\rudnei.oliveira\AppData\Local\atom\app-1.0.11\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (C:\Users\rudnei.oliveira\.atom\packages\atom-aligner-0.16.0\lib\operator-config.coffee:2:11)
    at Object.<anonymous> (C:\Users\rudnei.oliveira\.atom\packages\atom-aligner-0.16.0\lib\operator-config.coffee:1:1)
    at Module._compile (module.js:452:26)
    at Object.defineProperty.value [as .coffee] (C:\Users\rudnei.oliveira\AppData\Local\atom\app-1.0.11\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:347:32)
```

### Commands

```
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by adrianlee44** [comment]
This should be fixed with v0.16.1. Did you see the bug after restarting Atom?

**Comment by NullVoxPopuli** [comment]
I still get the error "Failed to load the asigner package"

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: linux 4.2.0-35-generic
**Thrown From**: [aligner](https://github.com/adrianlee44/atom-aligner) package, v0.21.0

### Stack Trace

Failed to load the aligner package

```
At /home/lprestonsegoiii/.atom/packages/aligner/lib/main.js:15
class Aligner {
^^^^^
Unexpected reserved word

/home/lprestonsegoiii/.atom/packages/aligner/lib/main.js:15
class Aligner {
^^^^^
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:75:16)
    at Module._compile (module.js:458:25)
    at Object.loadFile [as .js] (/usr/share/atom/resources/app/src/babel.js:162:21)
    at Module.load (module.js:370:32)
    at Function.Module._load (module.js:325:12)
    at Module.require (module.js:380:17)
    at require (module.js:399:17)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app/src/package.js:672:34)
    at /usr/share/atom/resources/app/src/package.js:189:28
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:167:15)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-ember-script",
      "atom-emblem",
      "es6-javascript"
    ],
    "themes": [
      "neutron-ui",
      "one-dark-syntax"
    ],
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
aligner, v0.21.0
aligner-ruby, v1.4.0
autocomplete-ruby, v0.1.0
linter-jscs, v3.5.0
neutron-ui, v0.4.0
tree-view-git-status, v0.2.3

# Dev
No dev packages
```

**Comment by adrianlee44** [comment]
@NullVoxPopuli, thanks for reporting. Any chance you can update Atom to the latest version, [1.7.2](https://github.com/atom/atom/releases/tag/v1.7.2)?

**Comment by NullVoxPopuli** [comment]
that was it! thanks! :-)
